import { formatDate } from "./formatDate";

export const generateSitemapIndexGenerator = (baseUrl, sitemapList) => {
  const currentDate = new Date();
  const sitemapIndex = `<?xml version="1.0" encoding="UTF-8"?>
    <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
      ${sitemapList
        .map((sitemap) => {
          return `
          <sitemap>
          <loc>${baseUrl}${sitemap.fileName}</loc>
          <lastmod>${formatDate(currentDate)}</lastmod>
        </sitemap>
          `;
        })

        .join("")}
    </sitemapindex>
<!-- XML Sitemap generated by İlyas Bozdemir  Simple Sitemap V1.0.0 -->
    `;
    return sitemapIndex
};
